# Server
server.address=0.0.0.0
server.port=8080
server.servlet.session.timeout=1h
server.servlet.session.cookie.name=lyrasuite_session
# Logging
logging.level.root=INFO
logging.level.com.xyuxu.javasec=DEBUG

myapp.admin.username=admin
myapp.admin.password=admin123
